### ISSUE TITLE
add to this repository the three files .json, .xml, .yml that represent the content table

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/dynamic_tables#3]
It will be good to have the three different formats (.json, .XML and .yml) of the content rendered by the dynamic table in the same repository. In this case, it is easy to do test by changes the the content on each of the tables,

**Comment by ladyvargas** [comment]
XML
[https://github.com/standards-hub/dynamic_tables/blob/main/ddf_sample.xml](url)
JSON
[https://github.com/standards-hub/dynamic_tables/blob/main/cim_subject_areas_library.json](url)
YML
https://github.com/standards-hub/dynamic_tables/blob/main/index.markdown

**Comment by jpradocueva** [comment]
Great! This is really good progress and a feature to add to our toolbox! Well done!
